<div class="page">    
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escape($title); ?></h3>
            </div>
            <div class="panel-body clearfix">
                <?php echo $content; ?>                
            </div>
        </div>

    </div>
</div>
<div class="clearfix"></div>