<?php
//$this->css($this->assetModule('admin/admin.css', 'system'));
?>
<div class="table-responsive">
    <form action="<?php echo $this->url('', array('action' => 'edit')); ?>">
        <table class="table">
            <thead>
            <tr>
                <!-- <th style="width: 5%;"><?php echo _a('Name'); ?></th> -->
                <th style="width: 10%;"><?php echo _a('Resource Title'); ?></th>
                <th style="width: 10%;"><?php echo _a('Resource Icon'); ?></th>
                <th style="width: 30%;"><?php echo _a('Resource Summery'); ?></th>
                <th><?php echo _a('Action'); ?></th>
                <th style="width: 5%;"></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item) { ?>
                <tr>
                    <td>
                        <?php echo _escape($item['title']); ?>
                    </td>
                    <td>
                        <img src="<?php echo _escape($item['icon']); ?>" width="80px" />
                    </td>
                    <td>
                        <?php echo _escape($item['description']); ?>
                    </td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-sm btn-primary" href="<?php echo $this->url('', array('action' => 'download', 'id' => $item['id'])); ?>"><?php echo _a('Download'); ?></a>

                                <!--                                <a class="btn btn-sm btn-warning" href="--><?php //echo $this->url('', array('action' => 'activate', 'id' => $item['id'])); ?><!--">--><?php //echo _a('Enable'); ?><!--</a>-->
                            <?php }?>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</div>
