<?php
$this->css($this->assetTheme('css/white-paper.css'));
?>
<div class="white-paper module-container clearfix">
    <div class="row">
        <?php foreach ($items as $item) { ?>
                <div class="media col-md-12">
                    <a class="pull-left" href="<?php echo $this->escape($item['url']); ?>">
                        <img style="width: 260px; height: 160px;" class="media-object" src="<?php echo $this->escape($item['icon']); ?>">
                    </a>
                    <div class="media-body paper-container">
                        <h4 class="media-heading"><?php echo _escape($item['title']); ?></h3>
                        <p class="app-summary">
                            <?php echo $this->escape($item['description']); ?>
                        </p>
                    </div>

                    <a class="btn btn-sm btn-success" href="<?php echo $this->url('', array('action' => 'download', 'id' => $item['id'])); ?>"><?php echo _a('Download'); ?></a>
                </div>
        <?php } ?>
    </div>
</div>
<div class="clearfix"></div>