<?php
    $this->jQuery();
    $this->Backbone();
?>

<div class="row-fluid">
    <div class="span12">
        <div id="pi-js-list">
            <table class="table table-striped">
                <tbody>
                <tr>
                    <th style="width:25%;">
                    <?php echo _a('Title'); ?></th>
                    <th style="width: 15%"><?php echo _a('Icon'); ?></th>
                    <th style="width: 40%"><?php echo _a('App Description'); ?></th>
                    <th><?php echo _a('Time published'); ?></th>
                </tr>
                <?php $now = time(); ?>
                <?php for ($i = 1; $i <= $appsCont; $i++) { ?>

                <?php
                // Get Id.
                $appId = 'solution_app[' . $i . '][id]';
                $appElementId = $form->get($appId);
                $appElementId->setAttribute("class", "check-one");
                ?>
                <tr data-id="<?php echo $i; ?>">
                    <td>
                        <?php echo $this->formElement($appElementId);?>

                        <?php
                        $appApp = 'solution_app[' . $i . '][app]';
                        $appElementApp = $form->get($appApp);
                        echo $this->formElement($appElementApp);
                        ?>
                    </td>
                    <td>
                        <?php
                        // Get Id.
                        $appIcon = 'solution_app[' . $i . '][icon]';
                        $appElementIcon = $form->get($appIcon);
                        echo $this->formElement($appElementIcon);
                        ?>
                    </td>
                    <td>
                        <?php
                        // Get Id.
                        $appDescription = 'solution_app[' . $i . '][description]';
                        $appElementDescription = $form->get($appDescription);
                        $appElementDescription->setAttribute("style", "width: 100%;");
                        echo $this->formElement($appElementDescription);
                        ?>
                    </td>
                    <td>
                        <?php
                        // Get Id.
                        $appPublish = 'solution_app[' . $i . '][publish]';
                        $appElementPublish = $form->get($appPublish);
                        echo $this->formElement($appElementPublish);
                        ?>
                    </td>
                </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
(function($) {
    var page = {
        url     : "<?php echo $this->url('', array(
            'controller' => 'solution',
            'action'     => ''
        )); ?>" . replace(/\/$/,""),
        el      : $("#pi-js-list"),
        $       : function(selector){
            return this.el.find(selector);
        },
        init    : function() {
            _.bindAll(this);
            this.$(".check-all").click(this.checkAll);
            this.$(".check-one").click(this.clickOne);

        },
        checkAll : function() {
            var flag=this.$(".check-all").prop("checked");
            this.$(".check-one").prop("checked",flag).each(function(){
                var tr=$(this).parents("tr:first");
                if(flag){
                    tr.addClass("info");
                }else{
                    tr.removeClass("info");
                }
            });
        },

        encodeUrl   : function() {
            return encodeURIComponent(location.href);
        },

        renderMessage : function(status, message) {
            $('#message-box').html(
                _.template($('#template-message').html(), {
                    status      : status ? 'success' : 'error',
                    message     : message
                })
            );
        }
    }
    page.init();
})(jQuery)
</script>
