<?php
$this->css($this->assetTheme('css/app.css'));
/*
$nav= array(
    array("active"=>"1","url"=>"#","title"=>"信息发布"),
    array("active"=>"0","url"=>"#","title"=>"产品概述"),
    array("active"=>"0","url"=>"#","title"=>"用户管理"),
    array("active"=>"0","url"=>"#","title"=>"二维码管理"),
    array("active"=>"0","url"=>"#","title"=>"资源管理"),
    array("active"=>"0","url"=>"#","title"=>"消息管理")
);
$url = Pi::service('asset')->getAssetUrl('theme/social', 'image/weixin.png');
//d($url);
$apps_list= array(
    array("icon"=>$url,"url"=>"#","title"=>"信息发布","summery"=>"安静了快点放假啦地方安静了卡机的法律安静的弗兰克爱的解放路口阿的说法刻录机啦地方安静了卡机的法律安静的弗兰克爱的解放路口阿的说法刻录机啦地方安静了卡机的法律安静的弗兰克爱的解放路口阿的说法刻录机"),
    array("icon"=>$url,"url"=>"#","title"=>"产品概述","summery"=>"安静了快点放假啦地方安静了卡机的法律安静的弗兰克爱的解放路口阿的说法刻录机"),
    array("icon"=>$url,"url"=>"#","title"=>"用户管理","summery"=>"安静了快点放假啦地方安静了卡机的法律安静的弗兰克爱的解放路口阿的说法刻录机"),
    array("icon"=>$url,"url"=>"#","title"=>"二维码管理","summery"=>"安静了快点放假啦地方安静了卡机的法律安静的弗兰克爱的解放路口阿的说法刻录机啦地方安静了卡机的法律安静的弗兰克爱的解放路口阿的说法刻录机"),
    array("icon"=>$url,"url"=>"#","title"=>"资源管理","summery"=>"安静了快点放假啦地方安静了卡机的法律安静的弗兰克爱的解放路口阿的说法刻录机"),
    array("icon"=>$url,"url"=>"#","title"=>"消息管理","summery"=>"安静了快点放假啦地方安静了卡机的法律安静的弗兰克爱的解放路口阿的说法刻录机啦地方安静了卡机的法律安静的弗兰克爱的解放路口阿的说法刻录机啦地方安静了卡机的法律安静的弗兰克爱的解放路口阿的说法刻录机"),
);
*/
?>

<div class="module-container clearfix">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked nav-font">
        <?php foreach ($nav as $id => $item) { ?>
            <li <?php if (!empty($item['active'])) { echo ' class="active"'; }?>>
                <a href="<?php echo $item['url']; ?>"><?php echo _escape($item['title']); ?></a>
            </li>
        <?php } ?>
        </ul>
    </div>
    <div class="col-md-10">
            <div class = "row">
                <div class="col-md-12">
                    <div class="summery-title"><?php echo $this->escape($title); ?></div>
                    <div class="summery-content"><?php echo $content; ?></div>
                </div>
            </div>
            <div class = "row">
                <div class="col-md-12">
                    <div class="list-title">
                        <?php if (!empty($apps_list)) { echo '产品模块'; }?>
                    </div>
                    <div class="row">
                        <?php foreach ($apps_list as $item) { ?>
                                <div class="media col-md-6">
                                    <div class="app-title">
                                        <a href="<?php echo $this->escape($item['url']); ?>">
                                            <?php echo $this->escape($item['title']); ?>
                                        </a>
                                    </div>
                                    <a class="pull-left" href="<?php echo $this->escape($item['url']); ?>">
                                        <img style="width: 88px; height: 88px;" class="media-object" src="<?php echo $this->escape($item['icon']); ?>">
                                    </a>
                                    <div class="media-body app-container">
                                        <p class="app-summary">
                                            <?php echo $this->escape($item['summery']); ?>安静了快点放假啦地方安静了卡机的法律安静的弗兰克爱的解放路口阿的说法刻录机
                                        </p>
                                    </div>
                                    <div class="app-more"><a href="<?php echo $this->escape($item['url']); ?>">了解更多</a></div>
                                </div>
                        <?php } ?>
                    </div>
                    </div>
                </div>
            </div>
    </div>
</div>
<div class="clearfix"></div>




