<?php
    $this->jQuery('extension/fileupload-min.js');
    $locale = Pi::config('locale');
    if (strpos($locale, '-')) {
        $list = explode('-', $locale, 2);
        $locale = $list[0] . '-' . strtoupper($list[1]);
    }
    //$datepickerLocale = sprintf('datepicker/locales/bootstrap-datepicker.%s.js', $locale);
    /*$this->bootstrap(array(
        'datepicker/datepicker.css',
        'datepicker/bootstrap-datepicker.js',
        $datepickerLocale,
        'js/bootstrap-typeahead.js',
    ));*/
    $this->css(Pi::service('asset')->getPublicUrl('vendor/bootstrap/datepicker/datepicker.css'));
    $this->js(Pi::service('asset')->getPublicUrl('vendor/bootstrap/datepicker/bootstrap-datepicker.js'));
    $this->js(Pi::service('asset')->getPublicUrl('vendor/bootstrap/datepicker/locales/bootstrap-datepicker.zh-CN.js'));
?>
<script>
   $(document).ready(function(){
     $('#start').datepicker({
        dateFormat:'yy-mm-dd',
        onSelect: function( startDate ) {
            var $startDate = $( "#js-start-time" );
            var $endDate = $('#js-end-time');
            var endDate = $endDate.datepicker( 'getDate' );
            if(endDate < startDate){
                $endDate.datepicker('setDate', startDate - 3600*1000*24);
            }
            $endDate.datepicker( "option", "minDate", startDate );
        }
     });
     $('#end').datepicker({
        dateFormat:'yy-mm-dd',
        onSelect: function( endDate ) {
            var $startDate = $( "#js-start-time" );
            var $endDate = $('#js-end-time');
            var startDate = $startDate.datepicker( "getDate" );
            if(endDate < startDate){
                $startDate.datepicker('setDate', startDate + 3600*1000*24);
            }
            $startDate.datepicker( "option", "maxDate", endDate );
        }
     });
   });
</script>
<form action="<?php $this->url('admin', array('action' => 'index')) ?>" method="POST" class="form-inline">
    <?php echo __("From:");?>
    <input type="text" id="start" name="start" class="form-control">
    <?php echo __("To： <br>");?>
    <input type="text" id="end" name="end" class="form-control">
    <input class="btn btn-primary" name="submit" type="submit" value="<?php echo __('Search'); ?>"  onclick=""/>
    <a class="btn btn-primary" href="<?php echo $this->url('admin', array('action' => 'export')) ?>"><?php echo __('Export') ?></a>
</form>
<table class="table table-striped">
    <tr>
        <th><?php echo __('Id') ?></th>
        <th><?php echo __('Name') ?></th>
        <th><?php echo __('Title') ?></th>
        <th><?php echo __('Company') ?></th>
        <th><?php echo __('Email') ?></th>
        <th><?php echo __('Phone') ?></th>
    </tr>
    <?php
    foreach ($items as $item) {?>
        <tr>
            <td><?php echo $item['id'] ?></td>
            <td><?php echo $item['name'] ?></td>
            <td><?php echo $item['title'] ?></td>
            <td><?php echo $item['company'] ?></td>
            <td><?php echo $item['email'] ?></td>
            <td><?php echo $item['phone'] ?></td>
        </tr>
    <?php }?>
</table>
