<?php
$this->css($this->assetTheme('css/freetrial.css'));
?>
<script language="JavaScript">
    $(function(){
        $("#select-group").on("click","a",function(e){
            var ckList = $("input[name='checkbox']");
            if(this.innerHTML == "全选"){
                ckList.each(function(){
                    $(this).prop("checked",true);
                })
            }else{
                ckList.each(function(){
                    $(this).prop("checked",false);
                })
            }
        })
        $("#del-all").click(function(){
            var str="";
            var url="<?php echo $this->url("home") ?>";
            $("[name='checkbox'][checked]").each(function(){
                str+=$(this).val()+",";
            })
            //alert(url) ;
            $.post(
                url + 'freetrial/index/batchdelete/',
                {
                    ids:str
                },
                function (data) //回传函数
                {
                    alert(data.msg);
                    window.location.href=url + 'freetrial/';
                }, 'json'
            );
        })
    })
</script>
<div class="row freetrail">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <ul class="nav nav-pills pull-left" role="tablist" id="select-group">
                    <li role="presentation"><a href="#" role="tab" data-toggle="tab">全选</a></li>
                    <li role="presentation"><a href="#"  role="tab" data-toggle="tab">反选</a></li>
                </ul>
                <input id="del-all" type="button" class="btn btn-link" value="批量删除">
            </div>
        </div>
    </div>
</div>
<form action="<?php $this->url('admin', array('action' => 'index')) ?>" method="POST" role="form" class="form-inline">
    <select name="type" class="form-control">
        <option value="name" <?php echo $type == 'name' ? 'selected' : ''; ?>><?php echo __('Name') ?></option>
        <option value="company" <?php echo $type == 'company' ? 'selected' : ''; ?>><?php echo __('Company') ?></option>
        <option value="phone" <?php echo $type == 'phone' ? 'selected' : ''; ?>><?php echo __('Phone') ?></option>
    </select>
    <input class="form-control" name="keyword" type="text" value="<?php echo $keyword ?>" />
    <input class="btn btn-primary" name="submit" type="submit" value="<?php echo __('Search'); ?>" /><br>
</form>
<table class="table table-striped">
    <tr>
        <th></th>
        <th><?php echo __('Id') ?></th>
        <th><?php echo __('Name') ?></th>
        <th><?php echo __('Title') ?></th>
        <th><?php echo __('Company') ?></th>
        <th><?php echo __('Email') ?></th>
        <th><?php echo __('Phone') ?></th>
        <th><?php echo __('Time') ?></th>
        <th>操作</th>
    </tr>
    <?php foreach ($pages as $page) { ?>
        <tr>
            <td> <input type="checkbox" name="checkbox" value="<?php echo $page['id'] ?>"></td>
            <td><?php echo $this->escape($page['id']) ?></td>
            <td><?php echo $this->escape($page['name']) ?></td>
            <td><?php echo $this->escape($page['title']) ?></td>
            <td><?php echo $this->escape($page['company']) ?></td>
            <td><?php echo $this->escape($page['email']) ?></td>
            <td><?php echo $this->escape($page['phone']) ?></td>
            <td><?php echo $this->escape(_date($page['time'])) ?></td>
            <td>
                <a class="btn btn-sm btn-primary" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $page['id'])); ?>"><?php echo _a('Delete'); ?></a>
            </td>
        </tr>
    <?php } ?>
</table>
<?php
if (!empty($paginator)) {
    echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml');
}
?>