<div class="page">
    <?php if (!empty($nav)) { ?>
    <div class="col-md-2">
        <ul class="nav nav-pills">
        <?php foreach ($nav as $id => $item) { ?>
            <li class="col-md-12" <?php if (!empty($item['active'])) { echo ' class="active col-md-12"'; } ?>>
                <a href="<?php echo $item['url']; ?>"><?php echo _escape($item['title']); ?></a>
            </li>
        <?php } ?>
        </ul>
    </div>
    <div class="col-md-10">
    <?php } ?>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escape($title); ?></h3>
            </div>
            <div class="panel-body clearfix">
                <?php echo $content; ?>

                <div class="solution-body">

                    <div class="row">
                      <div class="col-sm-12">
                        <div class="row">
                        <?php foreach ($solutions_list as $item) { ?>
                          <div class="col-xs-8 col-sm-6">
                            <div class="media">
                                <img style="width: 80px; height: 80px;" class="pull-left" src="<?php echo $this->escape($item['icon']); ?>">
                                <div class="media-body">
                                    <a href="<?php echo $this->escape($item['url']); ?>" class="solution-front-title">
                                        <?php echo $this->escape($item['title']); ?>
                                    </a>
                                    <div class="muted solution-size12" style="margin-top: 5px;">
                                        <?php echo $this->escape($item['summery']); ?>
                                    </div>
                                </div>
                            </div>
                          </div>
                        <?php } ?>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="social-list text-left">
                    <ul class="list-inline">
                        <?php if(!empty($config['social_facebook'])) { ?>
                        <li class="social-facebook"><?php echo $this->facebook(); ?></li>
                        <?php } ?>
                        <?php if(!empty($config['social_twitter'])) { ?>
                        <li class="social-twitter"><?php echo $this->twitter(); ?></li>
                        <?php } ?>
                        <?php if(!empty($config['social_gplus'])) { ?>
                        <li class="social-gplus"><?php echo $this->plusone(); ?></li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>

    <?php if (!empty($nav)) { ?>
    </div>
    <?php } ?>
</div>
<div class="clearfix"></div>