<?php $this->css($this->assetModule('css/front.css','common')); ?>

<!-- Nav tabs -->
<div class="indexTab">
    <ul class="nav nav-tabs" role="tablist" id="indexTab">
      <li class="active">
        <a href="#marketing" role="tab" data-toggle="tab">营销</a>
        <span class="pi-navbar-caret pi-navbar-caret-tab"></span>
      </li>
      <li>
        <a href="#sell" role="tab" data-toggle="tab">销售</a>
        <span class="pi-navbar-caret pi-navbar-caret-tab"></span>
      </li>
      <li>
        <a href="#service" role="tab" data-toggle="tab">服务</a>
        <span class="pi-navbar-caret pi-navbar-caret-tab"></span>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade in active" id="marketing">
            <img src="<?php echo Pi::service('asset')->getAssetUrl('theme/social', 'image/index_tab1.png');?>" alt="marketing"/>

                <h3>文字的处理能力</h3>
                <p class="clearfix">
                 理解力，可以说是设计师最重要的技能之一。当你拿到项目的时候，要分析哪些文字是重要的，
                 哪些文字是次要的，那些是可以弱化的，这考验的是设计师对一切实物的判断力和理解力，从某方面来说也考研的是设计师的阅历。
                </p>
      </div>
      <div class="tab-pane fade" id="sell">
            <img src="<?php echo Pi::service('asset')->getAssetUrl('theme/social', 'image/index_tab1.png');?>" alt="sell"/>
            <h3>文字的处理能力</h3>
            <p class="clearfix">
             理解力，可以说是设计师最重要的技能之一。当你拿到项目的时候，要分析哪些文字是重要的，
             哪些文字是次要的，那些是可以弱化的，这考验的是设计师对一切实物的判断力和理解力，从某方面来说也考研的是设计师的阅历。
            </p>
      </div>
      <div class="tab-pane fade" id="service">
          <img src="<?php echo Pi::service('asset')->getAssetUrl('theme/social', 'image/index_tab1.png');?>" alt="service"/>
          <h3>文字的处理能力</h3>
          <p class="clearfix">
           理解力，可以说是设计师最重要的技能之一。当你拿到项目的时候，要分析哪些文字是重要的，
           哪些文字是次要的，那些是可以弱化的，这考验的是设计师对一切实物的判断力和理解力，从某方面来说也考研的是设计师的阅历。
          </p>
      </div>
    </div>
</div>
<script>
  $(function () {
    $('#indexTab a:first').tab('show');
  })
</script>