<?php
//$this->css($this->assetModule('admin/admin.css', 'system'));
?>
<div class="table-responsive">
    <form action="<?php echo $this->url('', array('action' => 'menu')); ?>">
    <table class="table">
        <thead>
        <tr>
            <th><?php echo _a('App title'); ?></th>
            <th style="width: 5%;"><?php echo _a('Icon'); ?></th>
            <th style="width: 5%;"><?php echo _a('App Summery'); ?></th>
            <th style="width: 15%;"><?php echo _a('Time Created'); ?></th>
            <th><?php echo _a('Action'); ?></th>
            <th style="width: 5%;"><?php echo _a('Nav Order'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($apps as $app) { ?>
            <tr>
                <td>
                    <a href="<?php echo $app['url']; ?>" target="_blank">
                    <?php echo _escape($app['title']); ?>
                    </a>
                </td>
                <td>
                    <img src="<?php echo _escape($app['icon']); ?>" style="width: 80px;"/>
                </td>
                <td>
                    <?php echo _escape($app['summery']); ?>
                </td>
                <td>
                    <?php echo _date($app['time_created']); ?>
                </td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-sm btn-primary" href="<?php echo $this->url('', array('action' => 'edit', 'id' => $app['id'])); ?>"><?php echo _a('Edit'); ?></a>
                        <a class="btn btn-sm btn-primary" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $app['id'])); ?>"><?php echo _a('Delete'); ?></a>
                        <?php if ($app['active']) { ?>
                        <a class="btn btn-sm btn-primary" href="<?php echo $this->url('', array('action' => 'activate', 'id' => $app['id'])); ?>"><?php echo _a('Disable'); ?></a>
                        <?php } else { ?>
                            <a class="btn btn-sm btn-warning" href="<?php echo $this->url('', array('action' => 'activate', 'id' => $app['id'])); ?>"><?php echo _a('Enable'); ?></a>
                        <?php }?>
                    </div>
                </td>
                <td>
                    <input type="text" name="order[<?php echo $app['id']; ?>]" value="<?php echo $app['nav_order']; ?>" class="form-control">
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
        <div class="text-right">
        <input type="submit" value="<?php echo _a('Nav Order'); ?>" class="btn btn-primary">
        </div>
    </form>
</div>
